config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'help' =>'static_pages#help'
  get 'about' =>'static_pages#about'
  get 'contact' =>'static_pages#contact'
  get 'signup' =>'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base

before_save{ self.email= email.downcase}
validates :name, presence: true, length: { maximum: 50}
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum:255},
					format: {with: VALID_EMAIL_REGEX},
					uniqueness: { case_sensitive: false}

has_secure_password
validates :password, lenght: {minimum: 6}


end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def hello
render text: "hello, blogwonder!"
end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def about
  	
  end

  def help
  end

  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

#Returns the full title on a per-page basis.

def full_title(page_title='')
	base_title = "Blogwonder is a blog demo app"
	if page_title.empty?
		base_title
	else
		"#{page_title} | #{base_title}"
	end
end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class= "footer">

	<small>
	Demo App Project by Grace Sojor
	</small>
	
	<nav>
		<ul>
		<li><%= link_to "About", '#'%> </li>
		<li><%= link_to "Contact", '#'%> </li>
		</ul>

	</nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class ="container">
		<%= link_to "Blogwonder","#", id: "logo" %>
			<nav>
				<ul class ="nav bar navbar-nav pull-right">
				<li><%= link_to "Home", '#' %></li>
				<li><%= link_to "Help", '#' %></li>
				<li><%= link_to "About", '#' %></li>
				<li><%= link_to "Login", '#' %></li>
			</ul>
			</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<%= render 'layouts/shim' %>

</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
<%= yield %>

<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<!DOCTYPE html>
		<h1>About</h1>
		<p>This is a simple blog system project by Grace Sojor. For questions, drop her an email at grace.sojor@gmail.com. Ciao!</p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help") %>
<!DOCTYPE html>
<h1>Help</h1>
<p>Ooopss. You have reached a non-updated Help page. We will update the content soon. </p>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>


<%= link_to image_tag("logo.png", alt: "Blog logo") %>
<div class ="center jumbotron">
	<h1>Blogwonder Demo App</h1>
	<h2>This is the home page for the Blogwonder system.</h2>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

</div>

app/views/static_pages/login.html.erb
<h1>StaticPages#login</h1>
<p>Find me in app/views/static_pages/login.html.erb</p>

app/views/users/new.html.erb
<% provide(:title,'Sign up') %>

<h1>Sign up</h1>
<p>This will be the sign up page for new users.</p>